/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package selectorcolor;

import java.awt.Color;

/**
 *
 * @author Manu
 */
public class SelectorColor extends javax.swing.JFrame {

    /**
     * Creates new form SelectorColor
     */
    public SelectorColor() {
        initComponents();
        jTextFieldTest.setBackground(Color.BLACK);
        jTextFieldTest.setForeground(Color.WHITE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelRojo = new javax.swing.JLabel();
        jLabelVerde = new javax.swing.JLabel();
        jLabelAzul = new javax.swing.JLabel();
        jSliderRojo = new javax.swing.JSlider();
        jSliderVerde = new javax.swing.JSlider();
        jSliderAzul = new javax.swing.JSlider();
        jTextFieldTest = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelRojo.setForeground(new java.awt.Color(255, 0, 0));
        jLabelRojo.setText("Rojo (0)");

        jLabelVerde.setForeground(new java.awt.Color(0, 255, 0));
        jLabelVerde.setText("Verde (0)");

        jLabelAzul.setForeground(new java.awt.Color(0, 0, 255));
        jLabelAzul.setText("Azul (0)");

        jSliderRojo.setMajorTickSpacing(50);
        jSliderRojo.setMaximum(255);
        jSliderRojo.setPaintLabels(true);
        jSliderRojo.setPaintTicks(true);
        jSliderRojo.setValue(0);
        jSliderRojo.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderRojoStateChanged(evt);
            }
        });

        jSliderVerde.setMajorTickSpacing(50);
        jSliderVerde.setMaximum(255);
        jSliderVerde.setPaintLabels(true);
        jSliderVerde.setPaintTicks(true);
        jSliderVerde.setValue(0);
        jSliderVerde.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVerdeStateChanged(evt);
            }
        });

        jSliderAzul.setMajorTickSpacing(50);
        jSliderAzul.setMaximum(255);
        jSliderAzul.setPaintLabels(true);
        jSliderAzul.setPaintTicks(true);
        jSliderAzul.setValue(0);
        jSliderAzul.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderAzulStateChanged(evt);
            }
        });

        jTextFieldTest.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldTest.setText("Texto de test");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSliderRojo, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE)
                    .addComponent(jSliderVerde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSliderAzul, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelRojo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelVerde, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAzul, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldTest))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabelRojo)
                .addGap(18, 18, 18)
                .addComponent(jSliderRojo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelVerde)
                .addGap(18, 18, 18)
                .addComponent(jSliderVerde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addComponent(jLabelAzul)
                .addGap(18, 18, 18)
                .addComponent(jSliderAzul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jTextFieldTest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSliderRojoStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderRojoStateChanged
        cambiarColor();
        jLabelRojo.setText("Rojo (" + jSliderRojo.getValue() + ")");
    }//GEN-LAST:event_jSliderRojoStateChanged

    private void jSliderVerdeStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVerdeStateChanged
     cambiarColor();
     jLabelVerde.setText("Verde (" + jSliderVerde.getValue() + ")");
    }//GEN-LAST:event_jSliderVerdeStateChanged

    private void jSliderAzulStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderAzulStateChanged
       cambiarColor();
       jLabelAzul.setText("Azul (" + jSliderAzul.getValue() + ")");
    }//GEN-LAST:event_jSliderAzulStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SelectorColor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SelectorColor().setVisible(true);
            }
        });
    }

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelAzul;
    private javax.swing.JLabel jLabelRojo;
    private javax.swing.JLabel jLabelVerde;
    private javax.swing.JSlider jSliderAzul;
    private javax.swing.JSlider jSliderRojo;
    private javax.swing.JSlider jSliderVerde;
    private javax.swing.JTextField jTextFieldTest;
    // End of variables declaration//GEN-END:variables

    private void cambiarColor() {
            int R, V, A;
            int CR, CV, CA;
            R = jSliderRojo.getValue();
            CR = 255 - R;
            V = jSliderVerde.getValue();
            CV = 255 - V;
            A = jSliderAzul.getValue();
            CA = 255 - A;
            jTextFieldTest.setBackground(new Color(R,V,A));
            jTextFieldTest.setForeground(new Color(CR, CV, CA));
    }
}
